### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by mitbal** [tfzhou/BINGObjectness#1]
Hi, I have cloned the code and followed the instruction closely to run the code. I have downloaded the VOC dataset and the corrected annotation and put it into the same folder (picture related).
![correct folder](https://cloud.githubusercontent.com/assets/326048/7453620/63f6e2a6-f26b-11e4-86eb-3510a05bdb51.png)

Then I tried to run the example_BINGSingle and I got this error.
![error example](https://cloud.githubusercontent.com/assets/326048/7453673/f7913c6e-f26b-11e4-9d97-927510459dc0.png)

So I tried to compile the code. But when I ran compile.m, I encountered another error. This error messages was printed on the terminal.

```
Warning: You are using gcc version "4.8.2".  The version
         currently supported with MEX is "4.4.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

In file included from /usr/include/c++/4.8/random:35:0,
                 from Objectness/Src/kyheader.h:29,
                 from Objectness/Src/DataSetVOC.cpp:1:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8/backward/strstream:51:0,
                 from Objectness/Src/kyheader.h:33,
                 from Objectness/Src/DataSetVOC.cpp:1:
/usr/include/c++/4.8/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
In file included from Objectness/Src/kyheader.h:109:0,
                 from Objectness/Src/DataSetVOC.cpp:1:
Objectness/Src/CmTimer.h: In member function ‘void CmTimer::Reset()’:
Objectness/Src/CmTimer.h:59:88: warning: format ‘%s’ expects a matching ‘char*’ argument [-Wformat=]
   printf("CmTimer '%s'is started during reset request.\n Only reset cumulative time.\n");

                                                                                        ^
In file included from Objectness/Src/DataSetVOC.cpp:2:0:
Objectness/Src/DataSetVOC.h: At global scope:
Objectness/Src/DataSetVOC.h:17:21: error: ‘>>’ should be ‘> >’ within a nested template argument list
  vector<vector<Vec4i>> gtTrainBoxes, gtTestBoxes; // Ground truth bounding boxes for training and testing images

                     ^
Objectness/Src/DataSetVOC.cpp: In member function ‘void DataSetVOC::loadDataGenericOverCls()’:
Objectness/Src/DataSetVOC.cpp:75:22: error: ‘>>’ should be ‘> >’ within a nested template argument list
   vector<vector<Vec4i>> gtBoxes(imgN);

                      ^
Objectness/Src/DataSetVOC.cpp: In static member function ‘static bool DataSetVOC::cvt2OpenCVYml(CStr&, CStr&)’:
Objectness/Src/DataSetVOC.cpp:160:22: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(CStr&)’
   ifstream f(yamlName); 

                      ^
Objectness/Src/DataSetVOC.cpp:160:22: note: candidates are:
In file included from Objectness/Src/kyheader.h:28:0,
                 from Objectness/Src/DataSetVOC.cpp:1:
/usr/include/c++/4.8/fstream:467:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/4.8/fstream:467:7: note:   no known conversion for argument 1 from ‘CStr {aka const std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.8/fstream:453:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:453:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8/fstream:427:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:427:11: note:   no known conversion for argument 1 from ‘CStr {aka const std::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’
Objectness/Src/DataSetVOC.cpp: In static member function ‘static void DataSetVOC::getXmlStrVOC(CStr&, std::string&)’:
Objectness/Src/DataSetVOC.cpp:203:21: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(CStr&)’
   ifstream fin(fName);

                     ^
Objectness/Src/DataSetVOC.cpp:203:21: note: candidates are:
In file included from Objectness/Src/kyheader.h:28:0,
                 from Objectness/Src/DataSetVOC.cpp:1:
/usr/include/c++/4.8/fstream:467:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT = char; _Traits = std::char_traits<char>; std::ios_base::openmode = std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode = ios_base::in)
       ^
/usr/include/c++/4.8/fstream:467:7: note:   no known conversion for argument 1 from ‘CStr {aka const std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.8/fstream:453:7: note: std::basic_ifstream<_CharT, _Traits>::basic_ifstream() [with _CharT = char; _Traits = std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:453:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/4.8/fstream:427:11: note: std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:427:11: note:   no known conversion for argument 1 from ‘CStr {aka const std::basic_string<char>}’ to ‘const std::basic_ifstream<char>&’

    mex: compile of ' "Objectness/Src/DataSetVOC.cpp"' failed.

Error using mex (line 206)
Unable to complete successfully.

Error in compile (line 19)
  eval( ['mex -O -c ' objPath 'DataSetVOC.cpp ' objPath 'CmFile.cpp ' ...
```

My computer is running Ubuntu 14.04 64 bit. The Matlab version is 2013a.

Do you have any suggestion on how to fix this? I am kind of stuck and running out of idea on how to run it.
Any help is greatly appreciated.
Thank you.

**Comment by tfzhou** [comment]
hi，I guess the main problem is that    the gcc compiler your Matlab used does not support c++11. You need a higher version gcc and do some configuration so that your matlab can use it.  If you have difficulties do this kind of configure, please let me know, and I will help you when I return my office tomorrow.
Best wishes,Tianfei zhou

发送自 Outlook

**Comment by WanyiLi** [comment]
I also meet the same problem. Did you solve it? My computer is running Ubuntu 14.04 64 bit. The Matlab version is 2014a.

**Comment by WanyiLi** [comment]
The "gcc compiler error" can be fixed as follows: 
(1)open mex_C++_glnxa64.xml  in the dir .matlab/R2014a/ , open mexopts.sh in the dir .matlab/R2014a/bin/
(2) change the CXXFLAGS=" -ansi  ... "  to   CXXFLAGS=" -std=c++11   ... ".

but another error occurs: 
Error using mex
Unknown file extension '.0'. when the opencv3.0.0 is used and 
Unknown file extension '.8'. when the opencv2.4.8 is used.

**Comment by WanyiLi** [comment]
Mr Zhou, could you help me to fix the issue?
Thank you!

**Comment by tfzhou** [comment]
I just forget this issue, sorry for that. So Let's focus on the first issue from @mitbal Did you train the model using trainBing mex file before you run the algorithm?

**Comment by tfzhou** [comment]
@WanyiLi I really have no idea about the problem you encountered "Unknown file extension '.0'. when the opencv3.0.0 is used.  I check my mexopts.sh configuration and find the information below. Your way of change may not be the solution.
![screenshot from 2015-05-30 23 31 08](https://cloud.githubusercontent.com/assets/5791480/7897982/ee640528-0723-11e5-8290-5403a847f1b6.png)

**Comment by tfzhou** [comment]
@WanyiLi If you solve the problem, please let me know. Or, I will debug this code on another machine tomorrow to find the solution.

**Comment by tfzhou** [comment]
Hi, I have fixed the issue by explicitly using the c++11 flag when compiling with g++. Please update and recompile the codes.

**Comment by WanyiLi** [comment]
@tfzhou  Do you meet the " Unknown file extension '.0' "?

**Comment by WanyiLi** [comment]
@tfzhou  Did you meet the " Unknown file extension '.0' " problem?

**Comment by tfzhou** [comment]
I have not encountered the problem ever. Did you undo the changes in your mexopts.sh file?

**Comment by WanyiLi** [comment]
@tfzhou  There is a issue similar to  " Unknown file extension '.0' " problem in the mexopencv project on https://github.com/kyamagu/mexopencv/issues/132 and it has been closed but I have not figure out the key point for the solution.

**Comment by WanyiLi** [comment]
@tfzhou Yes, I undid the changes in the mexopts.sh file.

**Comment by WanyiLi** [comment]
@tfzhou I only change the CXXFLAGS=" -ansi ... " to CXXFLAGS=" -std=c++11 ... "  in mex_C++_glnxa64.xml file. By doing this,  explicitly using the c++11 flag  is not needed.

**Comment by WanyiLi** [comment]
@tfzhou I only change the CXXFLAGS=" -ansi ... " to CXXFLAGS=" -std=c++11 ... " in mex_C++_glnxa64.xml file. By doing this, explicitly using the c++11 flag is not needed when compiling with g++.

**Comment by mitbal** [comment]
Hi,

I have cloned the newest code. It fixes the previous compilation error. However, I get new error in different place. Here is the terminal output when I run compile.m

```
In file included from BINGSingle.cpp:6:0:
Objectness/Src/Objectness.h: At global scope:
Objectness/Src/Objectness.h:22:49: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void getObjBndBoxesForTests(vector<vector<Vec4i>> &boxesTests, int numDetPerSize = 100);

                                                 ^
Objectness/Src/Objectness.h:23:53: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void getObjBndBoxesForTestsFast(vector<vector<Vec4i>> &boxesTests, int numDetPerSize = 100);

                                                     ^
Objectness/Src/Objectness.h:25:41: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void getRandomBoxes(vector<vector<Vec4i>> &boxesTests, int numD = 10000);

                                         ^
Objectness/Src/Objectness.h:28:49: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void evaluatePerClassRecall(vector<vector<Vec4i>> &boxesTests, CStr &saveName = "Plot.m", const int numDet = 1000);

                                                 ^
Objectness/Src/Objectness.h:29:53: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void evaluatePerImgRecall(const vector<vector<Vec4i>> &boxesTests, CStr &saveName, const int numDet = 1000);

                                                     ^
Objectness/Src/Objectness.h:30:47: error: ‘>>’ should be ‘> >’ within a nested template argument list
  void illuTestReults(const vector<vector<Vec4i>> &boxesTests);

                                               ^

    mex: compile of ' "BINGSingle.cpp"' failed.

Error using mex (line 206)
Unable to complete successfully.

Error in compile (line 37)
  eval(['mex BINGSingle.cpp' include lib objects ' CFLAGS="\$CFLAGS
  -fopenmp" LDFLAGS="\$LDFLAGS -fopenmp" ']);
```

I think the error now is coming from BINGSingle.cpp installation.

**Comment by tfzhou** [comment]
@mitbal If you read the error info carefully, you will locate the file "Objectness/Src/Objectness.h". Actually, the compiler viewed ">>" as the shifting operator in C++.

**Comment by jibweb** [comment]
@WanyiLi  : I also ran into the "Unknown file extension '.10' " problem. The link you found concerns the same issue, but in this case, you don't need to change the opencv.pc file as they suggest. Changing the lib variable to '-lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -lrt -lpthread -lm -ldl' in the compile.m, and modifying CFLAGS="\$CFLAGS -fopenmp" to CXXFLAGS="\$CXXFLAGS -std=c++11 -fopenmp" solved the compiling issue for me (I'm not sure why this line uses CFLAGS instead of CXXFLAGS but since CFLAGS is defined in mex_C_glnxa64.xml and not mex_C++_glnxa64.xml, I don't think the env var is available to the compiler here)
