### ISSUE TITLE
Matlab 2015a or later support

### ISSUE THREAD

**Issue by cookyecat** [tfzhou/BINGObjectness#3]
Maybe someone will use.

Since R2014a, mxCreateReference is no longer available. If you want to recompile the project, you will see `un... to mxCreateReference` error. To fix this, you can complete the function as follows:

In `BINGMultiple.cpp`, comment the line 39:
```
// extern "C" mxArray* mxCreateReference(mxArray*);
```
Then add the following:
```
struct mxArray_Tag_Partial {
    void *name_or_CrossLinkReverse;
    mxClassID ClassID;
    int VariableType;
    mxArray *CrossLink;
    size_t ndim;
    unsigned int RefCount; /* Number of sub-elements identical to this one */
};
mxArray *mxCreateReference(const mxArray *mx)
{
    struct mxArray_Tag_Partial *my = (struct mxArray_Tag_Partial *) mx;
    ++my->RefCount;
    return (mxArray *) mx;
}
```

reference: https://stackoverflow.com/questions/18847833/is-it-possible-return-cell-array-that-contains-one-instance-in-several-cells

**Comment by tfzhou** [comment]
Thanks. I will fix it or you can submit a pull request
